### ISSUE TITLE
Subdomain Configuration

### ISSUE THREAD

**Issue by mzellner** [IchHabRecht/TYPO3-hosts_pattern#1]
I have some problems with this extension related to the use of subdomains. It works with subdomain.domain.tld, but not when i enter the subdomain with www (www.subdomain.domain.tld). Maybe somebody know more how to configure it in the localconf file?

**Comment by Atomschinken** [comment]
If you have set all necessary domain records, try to change line 66 of Classes/Service/PatternService.php to: `$subdomain = implode('.', array_reverse($reverseHost));`

It works better for me.

**Comment by IchHabRecht** [comment]
Hi Atomschinken,

Thank you for the report and sorry for the very long delay. Could you give me a more detailed problem description? Currently I don't know which issue is solved with changing the line.

**Comment by Atomschinken** [comment]
Hi IchHabRecht,

iirc the problem was after splitting the hostname the parts are reversed to extract the domain.
So when the parts left are combined again for the subdomain they are not correctly ordered.

Example:
www.subdomain.test.de
Explode+reverse:
de
test
subdomain
www

Take the first two parts to get the domain name:
test.de

Now just imploding the rest to get the subdomain would result in this:
subdomain.www.test.de

Regards,

**Comment by IchHabRecht** [comment]
Hi Atomschinken,

Thank you for your detailed information. I'm happy to say that this issue was already fixed with commit 180e1a9. Unfortunately I haven't seen before that this issue is from 2014.
